### ISSUE TITLE
运行main.py以后无法获取手机屏幕

### ISSUE THREAD

**Issue by fred0m** [bbpp222006/Princess-connection#1]
atx安装正常，服务启动正常
adb可以正常连接，运行main.py后可以正常弹出plt的窗口，当上面没有任何内容，几秒后程序退出，没有错误信息
使用的是华为mate10 Android 10
已经忽略电池优化

**Comment by bbpp222006** [comment]
本项目中使用的所有opencv模板(就是img文件夹下面的一堆图片)都是在模拟器下540*960截图的. 所以在其他分辨率下可能会匹配不上, 或是有各种各样的问题.... 不建议在手机上运行, 当然可以修改截图还有源码再进行测试

因为没有报错信息,所以只能给出以下建议.
1. 每次运行前检查atx服务,adb等是否正常启动.  `python -m uiautomator2 init`
2. 检查手机开发者模式下面是否允许了usb安装, 控制(模拟点击等)的权限(小米是有usb调试,安装,安全设置三个选项的)
3. 源码中使用uiautomator2链接的时候 ,加上ip地址d = u2.connect('192.168.1.103'),  ip地址会在小黄车应用中显示
4. 刚更新了test.py, 可以尝试运行看能否plt显示(记得把ip地址改了).  
5. 没有报错信息的话, 可以尝试用cmd运行文件`python test.py`

我在我的小米9上做了测试, 是可以得到截图的. 
![test](https://user-images.githubusercontent.com/34976166/79881339-a24e8c80-8423-11ea-84fb-5b74547349e8.jpg)

**Comment by fred0m** [comment]
我换了mumu模拟器，现在test.py可以正常返回分辨率和截图，但是main.py依然返回的是黑屏
![image](https://user-images.githubusercontent.com/41663893/79885701-f8263300-8429-11ea-81fe-f564e586c94e.png)

我在main中已经加上了mumu的ip地址
![image](https://user-images.githubusercontent.com/41663893/79885721-007e6e00-842a-11ea-9979-d766de4d5e9f.png)

但我zhanghao.txt没有改因为准备用游客号来刷不知道和这个有没有关系

**Comment by Clausy9** [comment]
出现了同样的问题，一切都运行正常，但是在运行main.py时，窗口会在几秒后消失（PS:使用的是MUMU模拟器，test.py返回的截图正常

**Comment by bbpp222006** [comment]
> 我换了mumu模拟器，现在test.py可以正常返回分辨率和截图，但是main.py依然返回的是黑屏
> ![image](https://user-images.githubusercontent.com/41663893/79885701-f8263300-8429-11ea-81fe-f564e586c94e.png)
> 
> 我在main中已经加上了mumu的ip地址
> ![image](https://user-images.githubusercontent.com/41663893/79885721-007e6e00-842a-11ea-9979-d766de4d5e9f.png)
> 
> 但我zhanghao.txt没有改因为准备用游客号来刷不知道和这个有没有关系

应该是这个问题, 现在还不支持游客号刷初始, 因为游客号登录有个验证码识别(现在还没做).

**Comment by fred0m** [comment]
> > 我换了mumu模拟器，现在test.py可以正常返回分辨率和截图，但是main.py依然返回的是黑屏
> > ![图片](https://user-images.githubusercontent.com/41663893/79885701-f8263300-8429-11ea-81fe-f564e586c94e.png)
> > 我在主要中已经加上了mumu的ip地址
> > ![图片](https://user-images.githubusercontent.com/41663893/79885721-007e6e00-842a-11ea-9979-d766de4d5e9f.png)
> > 但我zhanghao.txt没有改因为准备用游客号来刷不知道和这个有没有关系
> 
> 应该是这个问题，现在还不支持游客号刷初始，因为游客号登录有个验证码识别（现在还没做）。

我尝试去掉了那些关于账号登陆验证的函数，现在可以正常进入游戏并模拟点击了，但是进行到一半会出现一个使游戏退出并回到模拟器桌面操作（我手动测试后过场景没有出现闪退，所以应该是脚本模拟点击导致的）
估计可能是我的执行顺序有问题，请问在去掉所有账号登录操作和日志操作后这样的执行顺序对吗，是否需要修改呢？
![image](https://user-images.githubusercontent.com/41663893/79942322-25f69080-8499-11ea-8648-25c5b743a499.png)

**Comment by bbpp222006** [comment]
> > > 我换了mumu模拟器，现在test.py可以正常返回分辨率和截图，但是main.py依然返回的是黑屏
> > > ![图片](https://user-images.githubusercontent.com/41663893/79885701-f8263300-8429-11ea-81fe-f564e586c94e.png)
> > > 我在主要中已经加上了mumu的ip地址
> > > ![图片](https://user-images.githubusercontent.com/41663893/79885721-007e6e00-842a-11ea-9979-d766de4d5e9f.png)
> > > 但我zhanghao.txt没有改因为准备用游客号来刷不知道和这个有没有关系
> > 
> > 
> > 应该是这个问题，现在还不支持游客号刷初始，因为游客号登录有个验证码识别（现在还没做）。
> 
> 我尝试去掉了那些关于账号登陆验证的函数，现在可以正常进入游戏并模拟点击了，但是进行到一半会出现一个使游戏退出并回到模拟器桌面操作（我手动测试后过场景没有出现闪退，所以应该是脚本模拟点击导致的）
> 估计可能是我的执行顺序有问题，请问在去掉所有账号登录操作和日志操作后这样的执行顺序对吗，是否需要修改呢？
> ![image](https://user-images.githubusercontent.com/41663893/79942322-25f69080-8499-11ea-8648-25c5b743a499.png)

直接在原文件最后面修改就行,注释掉for循环, 三个函数调用放在最后, 如图.
![image](https://user-images.githubusercontent.com/34976166/79957526-454ee700-84b4-11ea-8a2d-17d80954acf2.png)
在游戏登录完成之后运行, 如果是新号的话应该会一直运行到抽完所有钻石.这边测试了一下,分辨率设置正常的话应该没有问题.  至于退回桌面这个情况,理论上应该不会发生, 可能是模拟器运行内存不够导致的闪退, 加大内存试试.
